# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fx/v1/currency.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'fx/v1/currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import date_pb2 as google_dot_type_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66x/v1/currency.proto\x12\x05\x66x.v1\x1a\x16google/type/date.proto\"\xe5\x01\n\x08\x43urrency\x12\'\n\x0f\x61lphabetic_code\x18\x01 \x01(\tR\x0e\x61lphabeticCode\x12!\n\x0cnumeric_code\x18\x02 \x01(\tR\x0bnumericCode\x12\x12\n\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n\x0bminor_units\x18\x04 \x01(\x05R\nminorUnits\x12\x1c\n\tcountries\x18\x05 \x03(\tR\tcountries\x12:\n\x0fwithdrawal_date\x18\x06 \x01(\x0b\x32\x11.google.type.DateR\x0ewithdrawalDate\"?\n\x0c\x43urrencyList\x12/\n\ncurrencies\x18\x01 \x03(\x0b\x32\x0f.fx.v1.CurrencyR\ncurrenciesBO\n\tcom.fx.v1B\rCurrencyProtoP\x01\xa2\x02\x03\x46XX\xaa\x02\x05\x46x.V1\xca\x02\x05\x46x\\V1\xe2\x02\x11\x46x\\V1\\GPBMetadata\xea\x02\x06\x46x::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx.v1.currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tcom.fx.v1B\rCurrencyProtoP\001\242\002\003FXX\252\002\005Fx.V1\312\002\005Fx\\V1\342\002\021Fx\\V1\\GPBMetadata\352\002\006Fx::V1'
  _globals['_CURRENCY']._serialized_start=56
  _globals['_CURRENCY']._serialized_end=285
  _globals['_CURRENCYLIST']._serialized_start=287
  _globals['_CURRENCYLIST']._serialized_end=350
# @@protoc_insertion_point(module_scope)
