# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fx/v1/provider.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'fx/v1/provider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66x/v1/provider.proto\x12\x05\x66x.v1\"\xac\x01\n\x08Provider\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12:\n\x19supported_base_currencies\x18\x03 \x03(\tR\x17supportedBaseCurrencies\x12<\n\x1asupported_quote_currencies\x18\x04 \x03(\tR\x18supportedQuoteCurrencies\"=\n\x0cProviderList\x12-\n\tproviders\x18\x01 \x03(\x0b\x32\x0f.fx.v1.ProviderR\tprovidersBO\n\tcom.fx.v1B\rProviderProtoP\x01\xa2\x02\x03\x46XX\xaa\x02\x05\x46x.V1\xca\x02\x05\x46x\\V1\xe2\x02\x11\x46x\\V1\\GPBMetadata\xea\x02\x06\x46x::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx.v1.provider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tcom.fx.v1B\rProviderProtoP\001\242\002\003FXX\252\002\005Fx.V1\312\002\005Fx\\V1\342\002\021Fx\\V1\\GPBMetadata\352\002\006Fx::V1'
  _globals['_PROVIDER']._serialized_start=32
  _globals['_PROVIDER']._serialized_end=204
  _globals['_PROVIDERLIST']._serialized_start=206
  _globals['_PROVIDERLIST']._serialized_end=267
# @@protoc_insertion_point(module_scope)
