# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fx/v1/quote.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'fx/v1/quote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import date_pb2 as google_dot_type_dot_date__pb2
from google.type import money_pb2 as google_dot_type_dot_money__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66x/v1/quote.proto\x12\x05\x66x.v1\x1a\x16google/type/date.proto\x1a\x17google/type/money.proto\"\xa3\x02\n\x05Quote\x12#\n\rprovider_code\x18\x01 \x01(\tR\x0cproviderCode\x12%\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x11.google.type.DateR\x04\x64\x61te\x12,\n\x12\x62\x61se_currency_code\x18\x03 \x01(\tR\x10\x62\x61seCurrencyCode\x12.\n\x13quote_currency_code\x18\x04 \x01(\tR\x11quoteCurrencyCode\x12$\n\x03\x61sk\x18\x05 \x01(\x0b\x32\x12.google.type.MoneyR\x03\x61sk\x12$\n\x03\x62id\x18\x06 \x01(\x0b\x32\x12.google.type.MoneyR\x03\x62id\x12$\n\x03mid\x18\x07 \x01(\x0b\x32\x12.google.type.MoneyR\x03mid\"1\n\tQuoteList\x12$\n\x06quotes\x18\x01 \x03(\x0b\x32\x0c.fx.v1.QuoteR\x06quotesBL\n\tcom.fx.v1B\nQuoteProtoP\x01\xa2\x02\x03\x46XX\xaa\x02\x05\x46x.V1\xca\x02\x05\x46x\\V1\xe2\x02\x11\x46x\\V1\\GPBMetadata\xea\x02\x06\x46x::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx.v1.quote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tcom.fx.v1B\nQuoteProtoP\001\242\002\003FXX\252\002\005Fx.V1\312\002\005Fx\\V1\342\002\021Fx\\V1\\GPBMetadata\352\002\006Fx::V1'
  _globals['_QUOTE']._serialized_start=78
  _globals['_QUOTE']._serialized_end=369
  _globals['_QUOTELIST']._serialized_start=371
  _globals['_QUOTELIST']._serialized_end=420
# @@protoc_insertion_point(module_scope)
