# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fx/currency.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'fx/currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import date_pb2 as google_dot_type_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66x/currency.proto\x1a\x16google/type/date.proto\"\x9b\x01\n\x08\x43urrency\x12\x17\n\x0f\x61lphabetic_code\x18\x01 \x01(\t\x12\x14\n\x0cnumeric_code\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0bminor_units\x18\x04 \x01(\x05\x12\x11\n\tcountries\x18\x05 \x03(\t\x12*\n\x0fwithdrawal_date\x18\x06 \x01(\x0b\x32\x11.google.type.Date\"-\n\x0c\x43urrencyList\x12\x1d\n\ncurrencies\x18\x01 \x03(\x0b\x32\t.Currencyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx.currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURRENCY']._serialized_start=46
  _globals['_CURRENCY']._serialized_end=201
  _globals['_CURRENCYLIST']._serialized_start=203
  _globals['_CURRENCYLIST']._serialized_end=248
# @@protoc_insertion_point(module_scope)
