# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fx/quote.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'fx/quote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import money_pb2 as google_dot_type_dot_money__pb2
from google.type import date_pb2 as google_dot_type_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66x/quote.proto\x1a\x17google/type/money.proto\x1a\x16google/type/date.proto\"\xdb\x01\n\x05Quote\x12\x15\n\rprovider_code\x18\x01 \x01(\t\x12\x1f\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x11.google.type.Date\x12\x1a\n\x12\x62\x61se_currency_code\x18\x03 \x01(\t\x12\x1b\n\x13quote_currency_code\x18\x04 \x01(\t\x12\x1f\n\x03\x61sk\x18\x05 \x01(\x0b\x32\x12.google.type.Money\x12\x1f\n\x03\x62id\x18\x06 \x01(\x0b\x32\x12.google.type.Money\x12\x1f\n\x03mid\x18\x07 \x01(\x0b\x32\x12.google.type.Money\"#\n\tQuoteList\x12\x16\n\x06quotes\x18\x01 \x03(\x0b\x32\x06.Quoteb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fx.quote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUOTE']._serialized_start=68
  _globals['_QUOTE']._serialized_end=287
  _globals['_QUOTELIST']._serialized_start=289
  _globals['_QUOTELIST']._serialized_end=324
# @@protoc_insertion_point(module_scope)
